#!/bin/bash
#SBATCH --job-name NISE_FD
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --time=0-06:00:00

module load foss

cd $SLURM_SUBMIT_DIR

#echo $TMPDIR
#cd $TMPDIR

time /scratch/p317440/Subroutines_branch_103_NISE/NISE_2017/bin/NISE inputFDCG
#/scratch/p317440/Subroutines_branch_103_NISE/NISE_2017/bin/2DFFT inputFDCG

#cp *.log $WD
#cp *.dat $WD
